### ISSUE TITLE
[BUG] Altitude hold maintains altitude 100ft below the selected altitude

### ISSUE THREAD

**Issue by ninjomcs** [saltysimulations/salty-747#104]
**Version of the mod**

2bd6c6b

**Describe the bug**

Altitude hold maintains the altitude 100ft below the selected altitude.

**To Reproduce**
1. Engage AP
2. Set altitude hold mode, or use V/S to climb / descend to the selected altitude.

**Expected behavior**

The aircraft should maintain the selected altitude.

**Screenshots**

![Microsoft_Flight_Simulator_Screenshot_2020 12 01_-_16 38 22 57](https://user-images.githubusercontent.com/26278705/101243294-773d5280-36ff-11eb-8a46-71fbb6a68e9f.png)

**Additional information**
Present in the default.

**Comment by airifr** [comment]
With altitude HOLD, the AP holds the actual altitude of the aircraft at the time the switch was pressed, irrespective of what the MCP altitude window shows. Say we set 35,000ft in MCP altitude window and the aircraft is climbing through 34,100ft when we press HOLD then the AP will stop the climb and return the aircraft to 34,100ft. With HOLD what's in the MCP altitude window is irrelevant, what's in the MCP altitude window is only meant for vertical path for the FMC and AP, ie VNAV VS and FLCH.
Of course if you're level at say 15,000ft with 15,000ft in MCP altitude window and press HOLD, the AP will hold 15,000, or if you're in climb or descent through 15,000ft it will return to 15,000ft and hold, not because 15,000ft is in the MCP altitude window but because the HOLD switch was pressed exactly as the aircraft passed 15000ft, as a coincidence.

**Comment by nhvtmedic** [comment]
Having the same issue. Set altitude to 39000 feet. Climb in V/S mode. Airplane cruises at 38,900. Also tried to correct by climbing then descending. Aircraft started cruising at 39,100. Cannot get it to go to 39,000 when set to 39,000.

**Comment by neshk16** [comment]
After testing, this is an Asobo Root Issue, I experienced it from the default 747 as well. Hopefully soon this will be solved.
