### ISSUE TITLE
V1 call and gpws not functioning

### ISSUE THREAD

**Issue by mikemikemike12** [saltysimulations/salty-747#146]
Hello

I dont get V1 call during takeoff and no gpws callouts during landing. No 50,40,30,20 and so on for example. I only get the callouts if I start the flight on the runway with the engines allready running. If I choose a gate from cold and dark startup and taxi out I dont get the V1 call or the altitude callouts during landing.
I tried using both the dev mod and the stable mod and no difference between them. With MSFS default 747 callouts are working.

**Version of the mod**

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by mikemikemike12** [comment]
only in the mod. Tried the default msfs 747 and the callouts worked

**Comment by DesertRick13** [comment]
@mikemikemike12  Which version of Salty are you running? Is it stable mod version 2.1, or one of the experimentals after 2.1? There was a comment about sound being left out of one of the expirimentals by accident which was fixed in a later mod. I wonder if you happened to download the mod  that was not fixed. Happy flying!

**Comment by mikemikemike12** [comment]
Hi 
I downloaded the experimentals via the master then code and then download a few days ago. Then I tried the stable 2,1 and still no sound.

**Comment by DesertRick13** [comment]
Have you now downloaded the newest Microsoft FS update (1.13.16)? if so, did that help?

**Comment by mikemikemike12** [comment]
Hi 
Downloaded dev mod again after updating and no difference. Thanks for quick replies and thanks for the mod!! Much better than default.

**Comment by 747-4EVER** [comment]
Very strange, I have seen a recent YouTube video using Dev from cold and dark and the sounds were working. Do you have any other add-ons running (even if you think they are nothing to do with the 747) as mods on MSFS conflict weirdly sometimes?

**Comment by Kriss047** [comment]
I also have the exact same problem, the only mods I have are the A32NX and some liveries for the 747.

**Comment by DesertRick13** [comment]
Have you tried moving the other mods out of the community folder? I have heard the A32 NX may have a conflict, which can be fixed by updating. All I know for sure is that it works for me, which isn't much help to you, I know. I suggest naming a temporary folder (my temp is communidad) and putting things there. Empty your community file into the temp, except the Salty. Fire up the sim with the Salty. If it works, you know that previous failure is due to conflict with another mod. If it still doesn't work, there is more digging to do.  If it does work, bring back the mods one by one until there is a failure, and you have found your culprit.

**Comment by ninjomcs** [comment]
anyone still having this issue feel free to tell us in discord, closing for now as it should be fixed
