### ISSUE TITLE
[REQUEST] Compatibility with Thrustmaster TCA Quadrant

### ISSUE THREAD

**Issue by dsuresh-ap** [saltysimulations/salty-747#163]
I have the Thrustmaster Airbus TCA quadrant (2 of them for 4 engines) but I could not find a native way to get the reversers working with the 747. Is it possible to get integration for this since it is a great throttle set for both Airbus and Boeing.

**Comment by DesertRick13** [comment]
One of the settings you can choose with the throttles is to actually have your idle partway up the control instead of fully back. When you pull it back from the new idle, it kicks into reverse thrust. I am in process of building my own throttle based on that setting. The other was is to map one button for both throttle axis for reverse. For instance, with my CH throttle, one axis is programmed four times (for engines 1,2,3, and 4), and one button and the axis move reverses thrust on all engines. Don't have the time to get specific about the name of the setting, but it is an option for throttle settings.

**Comment by dsuresh-ap** [comment]
@DesertRick13 Thanks for the suggestion I was able to get it working. My first issue was I set the axis to `Throttle Axis N` instead of `Throttle Axis N (0 to 100%)`. Then all I had to do was change the `Neutral` to `+43` and add some dead zone. Works perfectly, thanks!

![image](https://user-images.githubusercontent.com/21132682/111907227-c4cd9900-8a2a-11eb-9221-c927b33ad375.png)

![image](https://user-images.githubusercontent.com/21132682/111907236-ca2ae380-8a2a-11eb-9e66-4066e5f811bc.png)
