### ISSUE TITLE
[BUG] FMS not Displaying when Using APU to provide cockpit power.

### ISSUE THREAD

**Issue by SSK123z** [saltysimulations/salty-747#170]
**Version of the mod**
I am using the developer version.

**Describe the bug**
The bug is that the FMS/FMC is a black screen, with no way I can think of the turn it on.

**To Reproduce**
1. Spawn at a gate without external power
2. Start the APU to provide cockpit power. 

**Expected behavior**
The FMS/FMC should be lit up, and ready to input the data necessary.

**Screenshots**
![image](https://user-images.githubusercontent.com/80425233/115099696-28999380-9efd-11eb-81d9-4d79df06c123.png)
![image](https://user-images.githubusercontent.com/80425233/115099706-351dec00-9efd-11eb-9b96-b704a7fb8f03.png)

**References**
![image](https://user-images.githubusercontent.com/80425233/115099716-49fa7f80-9efd-11eb-9b80-9a89ac7ab05a.png)

**Additional information**
Is this bug present in the default 747-8, or only in the mod?
Only in the mod.

Your Discord: SSK123#8596

**Comment by Cassiano-Gunji** [comment]
It happened to me once. I restarted the flight without returning to the main menu and the FMC returned to work. At this moment, I'm flying again having spawned cold and dark. I turned on the battery and looked at the FMC and it was working correctly.

It seems this problem is either intermittent or has already been fixed.
