### ISSUE TITLE
with the dev version of salty 747 the flight plan line isn'tt showed at VFR map. Pls restore it, is very important to know if the flight plan is correctly loaded in map. thanks[BUG]

### ISSUE THREAD

**Issue by motishow** [saltysimulations/salty-747#272]
**Version of the mod**

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
unfortunately this is no longer possible with the WT FPM.

**Comment by giridat** [comment]
The flight plan line not showing is due to the new FPM system implemented which is from the Working Title team. This issue currently doesn't have a fix and it's not really upto us to fix it. 
Without this new FPM system you won't be able to make changes in your route, fly directs perform holding patterns. 

It is a request to you to not create a bug like this and follow the proper pattern of filing the bug. 
This bug I believe will occur with every aircraft that will use a custom FPM system.
