### ISSUE TITLE
Speed & hight inconsistent and unreliable

### ISSUE THREAD

**Issue by Qpanther** [saltysimulations/salty-747#279]
**Version of the mod**
latest dev version (announcement 27-07-21)

**Describe the bug**
In flight the plane's speed will become inconsistent and unreliable, in example: 1 moment she'll fly 260kts and the next minute she'll do a "hyperjump" and suddenly be at 340kts (includes overspeed). 2nd bug is that the altitude isn't taken into account as I've nearly hit the ground while the plane was on autopilot, still saying it was 5000ft above ground, while the system meanwhile warned me by voice that I was reaching 1000ft (yes, I double checked QNH etc). Lastly, importing flights from simbrief in the FMC doesn't work very stable, ACT RTE1 (initial retrieval) needs a double request send before showing accurately, then it also shows "activate" which shouldn't until the next page at "perf init" - there you need to request again in order to get the data for that page.

**To Reproduce**
Just fly, it should appear as is.

**Additional information**
Only in the mod version.

**Comment by ninjomcs** [comment]
your first issue seems like something to do with live weather or your weather configuration. your second issue doesn't sound like a bug to me? unless i'm misunderstanding, what you're saying is that you're at an altitude of 5000 feet, and the radioaltimeter says that you're at 1000 feet. this is very normal, as your altitude indicates your height **above the sea**, not above the ground. on the other hand, your radioaltimeter (the voice saying "1000") tells you your altitude **above the ground**. The first part of your third issue is likely a one-time thing, and i don't see anything wrong with the second part. "activate" should show on the route page, as the route and the perf are executed seperately, and the separate uplink for perf data is intentional.

**Comment by Qpanther** [comment]
> your first issue seems like something to do with live weather or your weather configuration. your second issue doesn't sound like a bug to me? unless i'm misunderstanding, what you're saying is that you're at an altitude of 5000 feet, and the radioaltimeter says that you're at 1000 feet. this is very normal, as your altitude indicates your height **above the sea**, not above the ground. on the other hand, your radioaltimeter (the voice saying "1000") tells you your altitude **above the ground**. The first part of your third issue is likely a one-time thing, and i don't see anything wrong with the second part. "activate" should show on the route page, as the route and the perf are executed seperately, and the separate uplink for perf data is intentional.

Seems like I've been too attached to the old config of the plane before the update which obviously differs from this version. 

Im leaving it to rest and will close it unless finding something worthy to argue about :-)

Thank you for your reply.
