### ISSUE TITLE
Terrain and airport map not shown on MFD

### ISSUE THREAD

**Issue by cedricyu803** [saltysimulations/salty-747#332]
### Version

v0.4.0, dev

### Describe the bug

I recently started flying the 747-8i. Alas, the Terrain and airport map are not shown on MFD when using the Salty mod V0.4.0, whether I start cold & dark, on the runway, or mid-air. I also tried the stable build; no luck. 
I tried reinstalling the base 747-8i, emptying out my Community folder and adding back the mods one by one. I got back the terrain and airport map on MFD as long as I put the Salty mod back in the Community folder. 
Thanks for your help

### Expected behaviour

Terrain and airport map should be available on MFD

### Steps to reproduce

1. Run MSFS with the Salty mod
2.

**Comment by giridat** [comment]
It is known and has been disabled by the Dev because it is unrealistic. 

![Screenshot_2021-09-19-19-13-15-010_com.discord.jpg](https://user-images.githubusercontent.com/61822722/134754671-4cbdcec2-7efb-4a94-8c31-d02dcda8d1fa.jpg) 

You can refer to this screenshot for re-activating it but expect no support for it if you face any issues.

[Issue to be closed]
